name: Merge Dependabot PRs
on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get PR Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Merge PR
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --merge ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Flag PR
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-major' }}
        run: "gh pr edit --add-assignee celsiusnarhwal --add-reviewer celsiusnarhwal ${{ github.event.pull_request.number }}"
