on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  publish:
    name: Publish to PyPI
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Publish Package
        uses: celsiusnarhwal/poetry-publish@dev
        with:
          python-version: 3.11.1
          poetry-version: 1.5.0
          build: true
          token: ${{ secrets.PYPI_TOKEN }}
